create table categories (
                            id          bigint generated by default as identity primary key,
                            user_id     uuid not null,
                            name        text not null,
                            constraint uq_categories_user_name unique (user_id, name)
);

create table transactions (
                              id          bigint generated by default as identity primary key,
                              user_id     uuid not null,
                              category_id bigint not null references categories(id),
                              type        text not null check (type in ('EXPENSE', 'INCOME')),
                              amount      numeric(12, 2) not null,
                              date        date not null,
                              note        text
);

create index idx_categories_user on categories(user_id);
create index idx_transactions_user on transactions(user_id);
create index idx_transactions_category on transactions(category_id);